name: memberlink_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  email_otp: ^3.0.2
  flutter:
    sdk: flutter
  http: ^1.2.2
  pinput: ^5.0.0
  shared_preferences: ^2.3.3
  crypto: ^3.0.1
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  badges: ^2.0.3
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.1.14
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  timeline_tile: ^2.0.0
  flutter_animate: ^4.5.0
  fl_chart: ^0.70.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
